baseurl = "http://winstonhoseadriggins.github.io/hugo-blog"
title = "DW84 Inc LLC BLOGPAGE"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Code released under the Apache 2.0 license."

[author]
    name = "Winston Hosea Driggins"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Everyone Has An Opinion!! Share Your Thoughts With A Blog!!"
  Author = "Winston Hosea Driggins"
  email = "wdriggins@gmail.com"
  Ganalytics = "XX-00000000-0"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/"
[[params.social]]
    title = "github"
    url = "https://github.com/winstonhoseadriggins"
[[params.social]]
    title = "facebook"
    url = "https://www.facebook.com/FACEBOOKHANDLE"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
